### ISSUE TITLE
Use InterMine color palette

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#10]

**Comment by AdrianBZG** [comment]
Color palette suggested by Yo: https://github.com/intermine/bluegenes/blob/dev/less/datatype-colors.less#L1-L57

**Comment by AdrianBZG** [comment]
@yochannah So do we want each of the filter boxes headers to have the background color in that palette, for instance? We'll discuss this after you return, no problem, just wanted to leave the message here.

**Comment by AdrianBZG** [comment]
@yochannah Can you give me a quick example to get the idea of what is desired with this issue? (if its still wanted to be done)

**Comment by yochannah** [comment]
I think it's probably safe to close actually - right now we don't have a
lot of intersection between the data types we allow filters for and the
colour scheme.

**Comment by AdrianBZG** [comment]
@yochannah All right! 👍
