### ISSUE TITLE
Query builder with automatically filled selectable fields

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#11]

**Comment by yochannah** [comment]
Let's use the following fields 
![image](https://user-images.githubusercontent.com/9271438/40314883-c2c97f78-5d11-11e8-9919-dd9b66a108b9.png)

**Comment by yochannah** [comment]
updating to add a few more fields - 
![image](https://user-images.githubusercontent.com/9271438/41295495-a0d161a4-6e52-11e8-957a-077f274b9f58.png)

Note that location will need some validation and should just be a set of coordinates

**Comment by AdrianBZG** [comment]
First step: auto-fill with Ontology > Name + filtering with it

**Comment by AdrianBZG** [comment]
@yochannah 

![lookahead1](https://user-images.githubusercontent.com/8275330/41494164-d76eae6e-710f-11e8-863e-a71bfb2fda92.png)

**Comment by AdrianBZG** [comment]
Hi @yochannah , filtering by ontology term, dataset name and/or pathway name is already working:

![image](https://user-images.githubusercontent.com/8275330/41511344-5b182216-7275-11e8-8d2c-d5c7606d89e5.png)

Can you please take a look and tell me what you think?

Thanks! 😄

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Next thing to do is filter by Locations > Start/End, and by Protein Domain Name

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Search by location Start and End is now working

![image](https://user-images.githubusercontent.com/8275330/42084458-ff879fea-7b8d-11e8-8eb6-c44274a274ae.png)

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Protein Domain Name filter is working (ba8db4f, 0e2e02c, 938ba3d):

![pdmfilter](https://user-images.githubusercontent.com/8275330/42154312-bd50b9f4-7de5-11e8-908f-86251b2dd18e.png)

http://im-browser-prototype.herokuapp.com/


I guess that this issue is now completed 😄 ❓

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Added Chromosome located on to the Locations filter as suggested by Rachel (#46)

![locatedonlocationfilter](https://user-images.githubusercontent.com/8275330/42207444-34d19678-7eaa-11e8-9e66-f484fc39c2b5.png)

👍
