### ISSUE TITLE
Study which flows of the interface can be added a 'save' functionality (see #16)

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#15]

**Comment by yochannah** [comment]
im-tables has a built in button to allow users to do this, so long as we have their api key - you can activate these buttons using the loadDash method.

Code: https://github.com/yochannah/im-tables-examples/blob/master/with-dashboard.html#L57 
Demo: https://yochannah.github.io/im-tables-examples/with-dashboard.html

![image](https://user-images.githubusercontent.com/9271438/43388487-2ca78a4c-93e1-11e8-9792-114edb458a4e.png)


(One thing to note: I have a feeling that keeping the data filters in sync with the filters, columns, and relationships button on the left side if this dash might be extremely difficult; I'd suggest using css to hide those buttons).

**Comment by yochannah** [comment]
Depends on #69

**Comment by AdrianBZG** [comment]
@yochannah This is not looking good, when using loadDash instead of loadTable, the 'rendered' is never being called, so it breaks everything... do you know why?

**Comment by AdrianBZG** [comment]
@yochannah Fixed, the table when using dashboard 'mode' is inside children element of the created object, specificially children.table. 😄
