### ISSUE TITLE
Enable save as list functionality

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#16]

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne We need to discuss if this is still an objective in Milestone 3 or not: maybe add another ones, remove this one, or modify it ❓ ❓ ❓ 

For all the goals in M3 check [https://github.com/AdrianBZG/InterMine-Data-Browser-Tool/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Milestone+3+%28August+6%29%22](https://github.com/AdrianBZG/InterMine-Data-Browser-Tool/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Milestone+3+%28August+6%29%22)

**Comment by AdrianBZG** [comment]
Optional, if time permits.

**Comment by yochannah** [comment]
I'd suggest allow users to paste in their own API token, store in localstorage, and use this to enable the save as list button (shown below)
![image](https://user-images.githubusercontent.com/9271438/43330119-30fb4454-91ba-11e8-969d-d4597a927c37.png)

**Comment by yochannah** [comment]
Depends on #69

**Comment by AdrianBZG** [comment]
@yochannah Done using token from /session, continuing this on #69
