### ISSUE TITLE
Add a 'switch' functionality to change between mines

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#21]

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Hi, I've made a quick test by changing the browser to work with FlyMine instead with HumanMine, and I've found that the following concepts, that work in HumanMine, don't exist in FlyMine ontology:

Gene.alleles.type + Gene.alleles.clinicalSignifance (Used for ClinVar filter)
Gene.proteinAtlasExpression.cellType + Gene.proteinAtlasExpression.tissue.name (Used in Protein Localisation filter)

Am I doing something wrong or indeed that filters are not applicable for FlyMine, for instance? The rest is working smoothly.

![image](https://user-images.githubusercontent.com/8275330/42850708-2d29280c-8a29-11e8-8d56-96dd65b07774.png)

Thanks.

**Comment by AdrianBZG** [comment]
Switching between mines is working but we are having problems due to concepts (for the filters) existing in HumanMine ontology that are not in the others.

**Comment by yochannah** [comment]
Actually, we were talking about this recently at the meeting! I think I remember you saying in the past that you were thinking of having json config for mine settings, is that right? We were thinking something along the lines of: 

1. Program defensively, _always_ checking if a filter / field exists before showing it on the left. 
2. There are some safe cross-mine defaults, such as organism, GO annotation, Dataset, and maybe pathway ( @rachellyne, am I talking truth?)
3. We'll create a ticket on InterMine itself to get a "default interesting fields" config that can be accessed via API. It might now be implemented by the time we have done with GSoC - it certainly won't be in many mines, regardless - so in the meantime we'd probably need to hard-code some basic per-mine configs. 

Does that make sense?

**Comment by rachellyne** [comment]
Yes, those are both examples that are specific to HumanMine.  I am struggling to know how this can be made generic as the data are just different between mines - that's the nature of biological data.  I think it would be better to make it more mine specific.

**Comment by rachellyne** [comment]
I think Yo just answered the question!

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne I think that for the moment, we can handle this by using the defensive approach, and instead of having the filter layout defined beforehand, use jQuery to dinamically add the filters during page load, checking if for the current mine, all the required fields exist. When the mine is switched, remove all the filters and reconstruct again. Only for those that are not GO annotation, dataset, organism and pathway.

Is there a way to check if a certain concept exists in a mine by querying the service, apart from catching that the response is a error code? For instance check if Genes.alleles.type exist?

Thanks 👍

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne The browser is now only showing the mines working with the default filters. Now we need to add the json file thing to add extra filters to those mines that can handle them.

[http://im-browser-prototype.herokuapp.com/](http://im-browser-prototype.herokuapp.com/)

**Comment by yochannah** [comment]
@AdrianBZG re checking if a path exists - not really. I've added it to the InterMine wishlist though https://github.com/intermine/intermine/issues/1866

**Comment by AdrianBZG** [comment]
🥇
