### ISSUE TITLE
Provide informative title for each of the routes and sub-routes 

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#22]
The filters for protein & genes at the top is great, but it's a little hard to tell which page you're on at any given time. Could we add a title, to the page? Perhaps something like "[datatype] in [minename]" e.g. "Proteins in HumanMine", "Genes in KittenMine" or something more generic for the landing page - perhaps "popular data types in HumanMine"

**Comment by yochannah** [comment]
when the genes / proteins filters are active up top they probably ought to be highlighted in some way - possibly by having a checkmark next to the active one and/or having the filters be white when not selected and coloured when they are (this can be tricky with only two as it's hard to tell which is highlighted and which isn't, which is why I suggest the checkmark as well).

**Comment by AdrianBZG** [comment]
Closed by 3d863ab and 218f0c6 👍
