### ISSUE TITLE
[pie chart] Add more descriptive title to pie chart

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#23]
The pie chart looks great! It might be nice to have a clearer description, e.g. perhaps "Number of results for [datatype, e.g. gene] by organism" rather than "General statistics". I do love the colours though! 

![image](https://user-images.githubusercontent.com/9271438/40718762-2474ce3c-6409-11e8-9522-d9a584d69d94.png)

**Comment by AdrianBZG** [comment]
Closed by 03ed9f9 :smile:
