### ISSUE TITLE
pie chart labels - is there room for numbers in the legend? [low priority]

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#26]
Lower priority, but probably can be done at the same time as #25 

The legend across the top is quite nice, but I wondered if there's room for numbers as well as the name of each colour label? e.g. `M. musculus, 80k`. 

It might be easier to put the labels across the side rather than along the top to make this fit on screens?

**Comment by AdrianBZG** [comment]
Done in 8db6f32
