### ISSUE TITLE
left bar filters - align text and numbers

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#27]
See screenshot - left bar filters are currently centre-aligned. Can we align the organism name on the left and the number on the right? 

![image](https://user-images.githubusercontent.com/9271438/40720392-785164e8-640e-11e8-88f4-4057a0854b16.png)

**Comment by AdrianBZG** [comment]
Closed by da8ac28 and a35089e🏅
