### ISSUE TITLE
left bar filters - color code [low priority]

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#28]
lower priority - can we color-code the left filter sidebar, perhaps with a thick left border, the same as the pie chart segments for consistency? 

E.g. in the screenshot below, H. sapiens could have an orange left-border, and D. melanogaster would have purple: 

![image](https://user-images.githubusercontent.com/9271438/40720614-3b58fa32-640f-11e8-88d7-c9e3e2613ffa.png)

If this is very time consuming then leave it for later, but if it's a quick addition it would be nice.

**Comment by AdrianBZG** [comment]
This was closed by 7433142 and c49e066
