### ISSUE TITLE
Things look a bit squishy on mobile & small screens

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#29]
Screenshot attached - the header shrinks nicely for small screens but could use a little bit of improvement where things overlap, and the pie chart seems to be missing entirely (maybe covered by the header?)

_Don't_ worry about imtables overspilling the screen - it's not terribly mobile friendly, but that's not the data browser's fault! so long as users can scroll sideways to see all of the imtable everything should be fine. 

![screenshot_20180530-134923](https://user-images.githubusercontent.com/9271438/40721158-9d97aec2-6410-11e8-9be9-483dbfa33b48.png)

**Comment by AdrianBZG** [comment]
@yochannah It looks nice now in small and mobile screen (0978bba), some examples:

My phone:

![photo_2018-06-15_01-00-50](https://user-images.githubusercontent.com/8275330/41442453-935cb3ca-7037-11e8-85de-5fd448b3db14.jpg)

Other devices:

![image](https://user-images.githubusercontent.com/8275330/41442180-357e32a2-7036-11e8-81f0-4c269f04bdc2.png)

![image](https://user-images.githubusercontent.com/8275330/41442182-385e183e-7036-11e8-9930-eb5d43f2084a.png)

![image](https://user-images.githubusercontent.com/8275330/41442184-3b812b8c-7036-11e8-8459-3f28e606cf25.png)

![image](https://user-images.githubusercontent.com/8275330/41442186-3df1665c-7036-11e8-9c3f-b2628ae4fd79.png)

**Comment by yochannah** [comment]
@AdrianBZG That is much better but the InterMine logo still gets covered by the dropdown a lot of the time in those screenshots. One option could be to just use a square logo (available here https://intermineorg.wordpress.com/logos/)

The navbar also sometimes covers the graph, like this, between screen widths of around 800px to 992px.

![image](https://user-images.githubusercontent.com/9271438/41459302-17f98772-7081-11e8-8625-8efc74899be0.png)

**Comment by AdrianBZG** [comment]
@yochannah I think it's good now (f5c69c7):

![image](https://user-images.githubusercontent.com/8275330/41460522-5a6ecb10-708d-11e8-9b9e-2dbf57485eae.png)

What do you think?

**Comment by yochannah** [comment]
that does look better - although could you double-check the aspect ratio of the logo is correct? it looks a little bit like it's being squished a bit, or it could be my eyes. I'm not sure ;)

**Comment by AdrianBZG** [comment]
@yochannah Probably you are right, since the height needs to be 37px... and maybe with 50px width is not correct, now it's 40px so it's almost a square... what do you think?

**Comment by yochannah** [comment]
For a height of 37 I think it probably needs a width of 36 - try that?

**Comment by AdrianBZG** [comment]
@yochannah What about now? 😄

**Comment by AdrianBZG** [comment]
@yochannah PS: For some reason Travis network is 💀 

PS2: 👍 now

**Comment by yochannah** [comment]
looks good!
