### ISSUE TITLE
HTTPS warning message flashes up for several seconds on load

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#31]
The message is good for https sites, but it shouldn't appear at all on the HTTP site - it shows for a second or two before going away when you load the page.

![image](https://user-images.githubusercontent.com/9271438/41460974-38028348-7086-11e8-9981-3bb2dc3cf7aa.png)

**Comment by AdrianBZG** [comment]
@yochannah What about now? 😄

**Comment by yochannah** [comment]
All good! :cake:
