### ISSUE TITLE
left filters - either auto-expand the filters or add an icon indicating they can be filtered

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#35]
it might be nice to suggest that the GO, Dataset, Pathway filters can be expanded using a `v` or `^` style icon - or just leave them expanded by default? I think there's room to leave them all open, at least on larger screens.

Either approach is fine.

**Comment by AdrianBZG** [comment]
@yochannah What do you think? 👍  or 👎  ?

http://im-browser-prototype.herokuapp.com/

**Comment by yochannah** [comment]
:+1:!
