### ISSUE TITLE
Make it easy to tell which filters are active at any given time 

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#38]
In the current screenshot, I assume that the following filters are active, but I'm not sure - 
1. GO annotation: "'de novo' protein folding"
2. Pathway: "Protein folding"
3. Organism: "H. Sapiens"

![image](https://user-images.githubusercontent.com/9271438/41534624-1293f984-72f7-11e8-9ae6-cfbe27b5f852.png)

Is this correct? If so, it might be nice to make it more visually clear. This could be by: 

- highlighting active filters
- removing the input box when a filter is active and just having the filtered property with a pencil and x beside it (for exit/remove)
- maybe some other way? open to options.

**Comment by AdrianBZG** [comment]
@yochannah Finished since #40 and #41 have been closed 😄
