### ISSUE TITLE
Show counts beside typeahead filters

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#39]
It would be nice to know how many of each result showing in my typeahead there are, similar to how organism works.

**Comment by AdrianBZG** [comment]
@yochannah Do you know how to query for {name, count} with the same query?

**Comment by yochannah** [comment]
I nearly came back to you and said I couldn't do it, but then I realised we just needed to do a summary query. Here's a demo: https://yochannah.github.io/im-tables-examples/nameandcount.html let me know if it doesn't make sense!

**Comment by AdrianBZG** [comment]
@yochannah Looks like I should be able to preprocess that summary response and associate the tuple {item,count} into a single string "item (count)" before feeding the typeahead, so it makes sense, thanks!
