### ISSUE TITLE
Dataset - change filter type

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#42]
For dataset, it might be easier to show a dropdown containing all options (there usually aren't that many, e.g. 10-20 datasets), or a set of checkboxes that allows multiple datasets to be chosen at once. 

For the checkbox option, we'd need to sort alphabetically and show only the top 5, with the option to "view more". Checkbox implementation might be related to #41

**Comment by AdrianBZG** [comment]
@yochannah I will check if I can query using offset for the dataset names.

**Comment by AdrianBZG** [comment]
@yochannah Done!: http://im-browser-prototype.herokuapp.com/

![image](https://user-images.githubusercontent.com/8275330/41824578-e30a1f4c-7812-11e8-934f-599fb537489b.png)
