### ISSUE TITLE
Consider adding formal api documentation comments

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#43]
The code is generally neat, tidy, and readable, but it might be nice to add some js api docs if possible too - it requires structured comments on functions. 

See https://github.com/documentationjs/documentation/blob/master/docs/GETTING_STARTED.md for an example - it's ok to consider other documentation tools if they suit you better though.

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne The code is now documented according to documentation.js, also a new gulp task to generate the documentation for the code in src/ and place it as HTML in the docs/ folder has been made available (gulp documentation). Also the documentation is available in GitHub pages at [https://adrianbzg.github.io/InterMine-Data-Browser-Tool/](https://adrianbzg.github.io/InterMine-Data-Browser-Tool/). 👍 

![image](https://user-images.githubusercontent.com/8275330/42294094-cbd94572-7fde-11e8-884f-afe790c4b9bf.png)

**Comment by yochannah** [comment]
This is great - thanks for adding it :) I am not at all worried about picking up this code in the future - it's so well documented it should hopefully be quite easy.

**Comment by AdrianBZG** [comment]
@yochannah Awesome!
