### ISSUE TITLE
Add chromosome located on to the Locations

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#46]
Add chromosome located on to Locations filter

Name it as "Chromosome"

**Comment by AdrianBZG** [comment]
Done in c9a768e 👍 

![locatedonlocationfilter](https://user-images.githubusercontent.com/8275330/42207361-09b86e4e-7eaa-11e8-859b-c6323f62195d.png)

**Comment by yochannah** [comment]
I can get this to work using the example in the screenshot above - nice one! 

Question for @rachellyne: when I try to copy regions from the region search in humanmine to search for in this tool I end up getting no results. After some investigation I realised the query is very precise, and you have to know the exact end and start coordinates - 

```xml
<query model="genomic" view="Gene.symbol Gene.name Gene.primaryIdentifier Gene.secondaryIdentifier Gene.length Gene.organism.name" >
   <constraint path="Gene.locations.start" op="==" value="2578486" />
   <constraint path="Gene.locations.end" op="==" value="2580016" />
   <constraint path="Gene.locations.locatedOn.primaryIdentifier" op="==" value="3" />
</query>
```

would it be better to find any genes that start or end in the specified region instead? You'd certainly know better than me.

**Comment by rachellyne** [comment]
Yes.  You need to put >, <. >=, <=  options on the search.

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Should we directly use >= for the Start constraints and <= for the End one, or add two selectables, with the 4 options >,<,>=,<= for each one?

**Comment by yochannah** [comment]
personally I'd prefer the first option - keeping the UI less complex - but @rachellyne would know better than me.

**Comment by rachellyne** [comment]
I think the first option should be fine.

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Done (268815e), check it out in http://im-browser-prototype.herokuapp.com/. If it proceeds, feel free to close this issue 😄 

![image](https://user-images.githubusercontent.com/8275330/42323420-70abe678-8060-11e8-9ee6-f3fde2bae331.png)
