### ISSUE TITLE
location search is buggy upon undo

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#48]
see screenshot - pressing undo will return to the previous search, but will leave the coordinates for location present in the search bar. Leaving them there implies the filter is still active (it isn't) and when you try to reset them, we get a little console error.
UI: 
![image](https://user-images.githubusercontent.com/9271438/42317400-3403482c-8044-11e8-962e-6625526e20ae.png)

Console: 
![image](https://user-images.githubusercontent.com/9271438/42317526-7f88da00-8044-11e8-8e8b-d5c463ed13c4.png)

To reproduce: try this search in location: `3:2578486..2580016`

**Comment by AdrianBZG** [comment]
@yochannah Is there a way to avoid im-table of showing the Undo message?

**Comment by yochannah** [comment]
not officially. I'd still like to show the message, as it is informative. We could be sneaky and do something like 

```css
.im-empty-apology .alert .btn {display:none}
```

to hide that button though :grin:

**Comment by yochannah** [comment]
is there any scenario in which the button *should* be used, btw, or is it better to force the user to use the filters on the left hand side?

**Comment by AdrianBZG** [comment]
@yochannah Yes, I just wanted to hide the button, since we are already handling the reset and removal of filters by ourselves, and that button is breaking the regular flow of the browser, since I can't control its behaviour. So perfect just hiding the button.

**Comment by AdrianBZG** [comment]
@yochannah I dont think the button should be required, since we already handle the filters by ourselves. 😄

**Comment by yochannah** [comment]
Sounds good!! :+1:

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne Fixed with b195e47 (http://im-browser-prototype.herokuapp.com/), if its ok, feel free to close this issue 👍

**Comment by yochannah** [comment]
looks good
