### ISSUE TITLE
Main dashboard front-end

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#5]

**Comment by AdrianBZG** [comment]
As first approach, we will design a general front-end with HumanMine in mind. In posterior milestones a 'switch' option to change between mines will be added.

**Comment by AdrianBZG** [comment]
Good example: https://dcc.icgc.org/search

**Comment by AdrianBZG** [comment]
Probably finished for Milestone 1? @yochannah

**Comment by yochannah** [comment]
@AdrianBZG I have a bit of feedback first before we close this. I've sent a mail to you about it - let me know how you'd prefer the feedback! :)

**Comment by AdrianBZG** [comment]
To-do: Use same border color for sidebar organisms as its in the pie chart

**Comment by AdrianBZG** [comment]
Last comment fulfilled with 7433142 😄

**Comment by AdrianBZG** [comment]
@yochannah I forgot to mention you about last comment in this issue 😄 , is it ok now?

**Comment by yochannah** [comment]
hmm, the buttons are pretty thick now - could we just do left border?

**Comment by AdrianBZG** [comment]
@yochannah Can you check the size now? http://im-browser-prototype.herokuapp.com/ ??

If its too bad, I can just use left border 😄

**Comment by yochannah** [comment]
Looks good!

**Comment by AdrianBZG** [comment]
@yochannah We agreed that this issue spans over the three milestones, and that for the first milestone, has been already done 👍

**Comment by AdrianBZG** [comment]
Changes in the dashboard for Milestone 2 are done, so I will remove the Milestone 2 tag and keep the Milestone 3 one, where maybe some new changes on the dashboard are added.

**Comment by AdrianBZG** [comment]
This is finished 😄
