### ISSUE TITLE
Chromosome search - some sort of loader?

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#50]
When I run a chromosome search, it takes several seconds before the im-tables loader bar appears, during which time I find myself wondering if I actually pressed the Go! button at all. Is there a way to make the im-tables loading bar load earlier, or some other way to indicate to the user that the browser is thinking?

**Comment by AdrianBZG** [comment]
@yochannah I will give this a thought

**Comment by AdrianBZG** [comment]
Moved to intermine repo, intermine#22
