### ISSUE TITLE
cancel old http requests / don't display old results that are no longer active filters

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#51]
I just ran a query that took a long time to return (which is fine, sometimes that just happens) and I got bored waiting for it to return. The search was a chromosome location search over something like `3:2098000-3059999`. It might be faster now that it's been run on the server once? 

Once I clicked reset I went and started to filter down a dataset.... and then the chromosome results came back, and updated the view! The screenshot below is definitely the results for genes in the chromosome search - see http://www.humanmine.org/humanmine/report.do?id=1264327 as an example.

We might need to do something like keeping track of which results are returned and whether or not they're still relevant. If this is tricky let me know your thoughts! 

![image](https://user-images.githubusercontent.com/9271438/42324226-79fcef20-805a-11e8-9bf3-178ecb54e33d.png)

**Comment by AdrianBZG** [comment]
@yochannah Just a question, when doing that, you got a error in console like "Did not remove a single constraint" ??

**Comment by AdrianBZG** [comment]
@yochannah I'm still trying to reproduce this, but im unable to 😢

**Comment by yochannah** [comment]
Whoops! It's okay to ignore it until I'm back in the office

**Comment by AdrianBZG** [comment]
@yochannah Ok! I hope we will manage to spot this bug when you are back 🤓

**Comment by yochannah** [comment]
I'll re-open this if I can reproduce it
