### ISSUE TITLE
ClinVar filter

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#52]

**Comment by AdrianBZG** [comment]
Example query given by @rachellyne:

```
<query name="" model="genomic" view="Gene.symbol Gene.name Gene.primaryIdentifier Gene.secondaryIdentifier Gene.organism.name Gene.alleles.primaryIdentifier Gene.alleles.organism.name Gene.alleles.clinicalSignificance Gene.alleles.alternate Gene.alleles.type Gene.alleles.reference Gene.alleles.diseases.identifier Gene.alleles.diseases.name" longDescription="For a gene, show alleles and any associated diseases. ClinVar data." sortOrder="Gene.symbol asc">
<constraint path="Gene" op="LOOKUP" value="PPARG" extraValue="H. sapiens"/>
</query>
```

**Comment by AdrianBZG** [comment]
@yochannah @rachellyne This filter is now working 👍 :

http://im-browser-prototype.herokuapp.com/

![clinvar1](https://user-images.githubusercontent.com/8275330/42527063-e94f05f4-8477-11e8-8dec-48cf23643486.png)

**Comment by rachellyne** [comment]
Looks great and worked!  Could you may be put an example in each box, as you have done for other filters?  e.g. Pathogenic for clinical significance and Insertion for type.

**Comment by AdrianBZG** [comment]
@rachellyne Done! 😉
