### ISSUE TITLE
small screen - filters aren't squishing down nicely

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#59]
screenshot: the x wraps strangely for the filter field. (Also, the pie is a bit covered). 
![image](https://user-images.githubusercontent.com/9271438/42935661-1bddbda0-8b42-11e8-97fb-62e42c73a994.png)

**Comment by yochannah** [comment]
Also the strange black bar
![image](https://user-images.githubusercontent.com/9271438/42937267-6f0274fe-8b46-11e8-8227-463bd39ad1d5.png)

**Comment by AdrianBZG** [comment]
@yochannah Yes, I will need to finish first #21, #58, #57 before dealing with the layout in small devices, but it will definetely be done

**Comment by AdrianBZG** [comment]
@yochannah The problem with the filters when adding them is fixed now

**Comment by AdrianBZG** [comment]
@yochannah Now it should correctly adapt to any screen dinamically, taking into account if the current mine has only a few or a lot of filters in the navbar 👍
