### ISSUE TITLE
Wishlist: Deep link to a specific mine

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#62]
This is low priority but would be nice if there's time - could we allow http://someurlto.the.databrowser.com/mine/FlyMine (or similar) to automatically link to the flymine version of the mine?

**Comment by AdrianBZG** [comment]
@yochannah Hi, this feature has been added, you can try with the following url for FlyMine (as an example):

[http://im-browser-prototype.herokuapp.com/mine/FlyMine](http://im-browser-prototype.herokuapp.com/mine/FlyMine)

👍
