### ISSUE TITLE
Wishlist: remember which mine you were looking at last time

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#63]
Low priority - 

If I'm always interested in Yeastmine, it should be a shame to have to choose it from the dropdown each time. A cookie or localstorage setting to save the last viewed mine could make this nicer.

**Comment by AdrianBZG** [comment]
@yochannah Hi, now the last visited mine (triggered by the mine selector dropdown) is saved in LocalStorage, and the next session will be loaded with that one, unless you access the browser using the mine-routing implemented in #62. 👍
