### ISSUE TITLE
handle an intermine being down

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#67]
FlyMine's having a little hiccup right now and that reminded me: if all the http requests error (and it's not https related) we should assume that the intermine in question is down right now. An error might be something like:

"Sorry, it looks like the FlyMine server is having problems right now. You can try coming back later, or try browsing a different mine using the mine selector in the top-right corner."

make sure that it is non-dismissable ;)

**Comment by AdrianBZG** [comment]
@yochannah Handling now an InterMine being down, what it does is, when a user selects a mine from the dropdown, it performs first a sanity check, if the sanity check is not passed, the browser doesn't react to the change and displays an error alert - dismissable, to let the user continue working with the browser.

Small test with a fake wrong url:

![a49e703db48520b0d5a522d06ac57a35](https://user-images.githubusercontent.com/8275330/43455821-6e3643be-94c1-11e8-82e0-7979da0d6bc4.png)

**Comment by yochannah** [comment]
perfect!
