### ISSUE TITLE
Mine selector - move to top left

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#68]
we'd like it to be slightly more in focus - can we move it to the top left instead of right? I wonder if we should also label it, e.g. "Select an InterMine"

**Comment by AdrianBZG** [comment]
@yochannah Done! 👍

![mineselector1](https://user-images.githubusercontent.com/8275330/43448311-e6b6d7cc-94ad-11e8-9953-cf88dff92bae.png)
