### ISSUE TITLE
Allow users to add their API tokens for each mine

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#69]
In order to save lists, users ought to be able to save their [personal API tokens](http://intermine.readthedocs.io/en/latest/web-services/authentication/#authentication-for-existing-user-accounts-permanent-tokens) to the data browser. I'd suggest a "sign in" button on the top right that allows the user to paste their token in, making it very clear that they need to paste in once per mine. 

something like: 

![blank diagram - page 1 1](https://user-images.githubusercontent.com/9271438/43393309-7c447cd8-93ee-11e8-90b4-bc2a2b2fa21b.png)

Save API keys in localstorage; I don't think we want to create a login infrastructure for this right now.

**Comment by AdrianBZG** [comment]
@yochannah This is working now 👍 

![image](https://user-images.githubusercontent.com/8275330/45269692-50e1cb80-b492-11e8-8c87-ba9f54079188.png)

![image](https://user-images.githubusercontent.com/8275330/45269694-53dcbc00-b492-11e8-8365-c4c0cf5c1486.png)

![image](https://user-images.githubusercontent.com/8275330/45269698-593a0680-b492-11e8-850d-58682286af9f.png)

[http://im-browser-prototype.herokuapp.com/](http://im-browser-prototype.herokuapp.com/)

**Comment by yochannah** [comment]
Looks briliant, and I love the guidance text here! (pausing for a moment as I just realised I like it because I wrote it in the mock up the top of this issue :rofl:) 

A few things: I might the "Paste your API key here" be a placeholder. This means the user doesn't have to delete the text. 

see screenshots: 

placeholder rather than value:
![image](https://user-images.githubusercontent.com/9271438/45310821-40c3fd80-b51f-11e8-866e-ceb71bae6ef5.png)

What it looks like (the top text in grey disappears when the user types)

![image](https://user-images.githubusercontent.com/9271438/45310881-70730580-b51f-11e8-86d4-d86f0e6fa5b4.png)

it might also be nice to make the page less whitespacey when it's on a small screen. 

I also tried to save a list after entering my flymine token and nothing happened - I couldn't see the list on flymine. Maybe I did something wrong?

**Comment by AdrianBZG** [comment]
@yochannah Oh, I will take a look and fix that in a moment, also will change it from value to placeholder. About the whitespacey thing, I don't know really know how to have it properly while maintaining the float-md-left and float-md-right of the elements (text + input) to keep them aligned, since once I do that, I need to add extra < br > to avoid overlapping, I will see if there is some other workaround.

**Comment by yochannah** [comment]
Try flexbox! I can help out with an example tomorrow if it has you stumped
:)

**Comment by AdrianBZG** [comment]
@yochannah Sure! I'll try with flexbox today and tell you if I don't manage to get it properly so you can enlighten me tomorrow 👍

**Comment by AdrianBZG** [comment]
@yochannah Done 😄 It works like a charm with flexbox, thanks. Also now uses the API key provided by the user to load the table, I've tested it with a public one:

![image](https://user-images.githubusercontent.com/8275330/45317971-d4a3c280-b53b-11e8-8e0a-507ae440dd83.png)

http://im-browser-prototype.herokuapp.com/

If you can confirm that it works, the issue can be closed.

**Comment by yochannah** [comment]
Looks good! 

I tried pasting a _bad_ key and the "save as list" button disappears. I'm guessing this might be imtables being intelligent since there are a bunch of console errors where imtables is getting upset :) anyway, disappearing the button with a bad key is good.

I have a few small improvements to suggest, but they're non-urgent - I'll make them tickets on the main intermine repo.
