### ISSUE TITLE
First iteration of code documentation

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#7]
In this first iteration of code documentation, the code related with the following tasks will be exhaustively commented, if not already:

- Main dashboard front-end.
- Server-side routes to query InterMine databases.
- Functional general statistics of the data with graphics and plots.

**Comment by yochannah** [comment]
How do we build the scss? might be nice to add to the readme.

**Comment by AdrianBZG** [comment]
Closed by 5054ff2 😄
