### ISSUE TITLE
Proteins page - fix various console errors 

### ISSUE THREAD

**Issue by yochannah** [AdrianBZG/InterMine-Data-Browser-Tool#70]
The proteins page has a large number of errors in the console - see 

![image](https://user-images.githubusercontent.com/9271438/43523512-83477088-9594-11e8-8222-16885c8afb17.png)

**Comment by AdrianBZG** [comment]
@yochannah Fixed, this was happening because the 'extra filters' are not suitable for the Protein class, it doesn't have the required ontology terms.
