### ISSUE TITLE
Searching data on HumanMine (issue #3 required)

### ISSUE THREAD

**Issue by AdrianBZG** [AdrianBZG/InterMine-Data-Browser-Tool#8]
Searching data on HumanMine (issue #3 required)

**Comment by AdrianBZG** [comment]
Potential classes:

- Gene
- Protein

**Comment by AdrianBZG** [comment]
Most important attributes: we can assume that the ones given by Summary are the most important ones for each class.

**Comment by yochannah** [comment]
To fetch summary fields using im.js, you just need to create a service, then run `fetchSummaryFields()` on the service object, like this:

```javascript
      var service = new imjs.Service({
         root: 'http://www.flymine.org/flymine/service'
     });
      service.fetchSummaryFields().then(function(response) {
        console.log(response)
      });
```

Working demo: http://jsbin.com/vipujej/edit?html,console

**Comment by AdrianBZG** [comment]
Whitelist for classes: https://github.com/intermine/bluegenes/blob/44777459217c51bfbac24fde6a26d818dfdb1122/src/cljc/bluegenes/whitelist.cljc#L3

**Comment by AdrianBZG** [comment]
HumanMine - Genes class: makes sense to use the fields Organism name, Gene name, and Gene symbol for the faceted search.

**Comment by AdrianBZG** [comment]
HumanMine - Proteins class: makes sense to use the field Organism name for the faceted search. Primary identifier and primary accession seem to be unique, so it doesn't make sense to use them as a filter.

**Comment by AdrianBZG** [comment]
@yochannah About my latest two comments to this issue, what do you think? With faceted search I mean, for instance, the boxes at the left that you can see in [https://dcc.icgc.org/search](https://dcc.icgc.org/search).

**Comment by yochannah** [comment]
Hmmm,  there isn't any easy way to tell this from the model. For Genes - name and symbol mostly unique, so they probably don't need be sidebar filters. Organism will always be interesting as a filter. I'll ask the team on monday morning if there are any other facets that they think might be interesting!

**Comment by AdrianBZG** [comment]
@yochannah Thanks! Also, do you know a way (using IMjs maybe), to query for the number of elements per value on a certain attribute of a class? Basically, what I want is what you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/8275330/40280069-523b077c-5c4e-11e8-9fd1-59e45d7fb5b9.png)

Mus musculus ... X
Homo sapiens ... Y
... and so on

Thanks!

**Comment by yochannah** [comment]
given any single query you can request a count of results like this: https://codepen.io/yochannah/pen/YLBGwa?editors=1012 but I'm not sure if that's what imtables is doing in the screenshot - it might be doing something a little bit smarter that doesn't require multiple http requests. I'll try to have a look when I'm at work tomorrow (pm, probably, since we have a team meeting in the morning) if you can wait 'til then?

**Comment by AdrianBZG** [comment]
@yochannah Of course! Thank you very much 😄

**Comment by yochannah** [comment]
I was right! It took some sleuthing, but here you go: https://codepen.io/yochannah/pen/MGLqyY?editors=1010 

``` javascript
var service = new imjs.Service({
  root: "https://yeastmine.yeastgenome.org/yeastmine/service"
});
var query = {
  from: "Gene",
  select: ["primaryIdentifier"],
  model: {name : "genomic"}
};

var q = new imjs.Query(query,service);

q.summarize("Gene.homologues.homologue.organism.shortName")
  .then(function(response) {
  console.log(response);
});

```

**Comment by yochannah** [comment]
it returns something like this: 
![image](https://user-images.githubusercontent.com/9271438/40312253-409aee4e-5d0a-11e8-980a-1d9b0ee87b01.png)

**Comment by yochannah** [comment]
The docs aren't always the most useful, but here is the reference for the summarise method: http://alexkalderimis.github.io/imjs/classes/Query.html#summarise-instance

**Comment by AdrianBZG** [comment]
@yochannah Perfect! Thanks 👍

**Comment by AdrianBZG** [comment]
@yochannah One question, if you take a look at the right side bar in [http://im-browser-prototype.herokuapp.com/](http://im-browser-prototype.herokuapp.com/), and click on Organism short names for instance, it displays each organism and the number of instances with that organism (currently is just a placeholder). My main concern is the following:

* Should this sidebar be used as a filtering option for the table data in the view or maybe, since the im-table already has the filtering options, we can use this sidebar to show top 5 elements (according to counts) ?

Thanks!

**Comment by yochannah** [comment]
Looking good! I think we like top 5 elements for organism, but probably we don't need gene name as a filter on the left.

**Comment by AdrianBZG** [comment]
Hi @yochannah , the filter by organism name is working, if you have some time can you please check it and tell me if I can close this issue? 

[http://im-browser-prototype.herokuapp.com](http://im-browser-prototype.herokuapp.com)

Thanks!

**Comment by yochannah** [comment]
The way the left filter works is great! it should probably be more integrated with the pie chart though - see https://github.com/AdrianBZG/InterMine-Data-Browser-Tool/issues/24

**Comment by yochannah** [comment]
looks good now
